import { ICurrency } from "~/types";

export const currencyList: ICurrency[] = [
  {
    id: 1,
    name: "BTC",
    symbol: "btc",
    quote: {
      USD: {
        price: 28089.287104060542,
        volume_24h: 14526222446.212822,
        market_cap: 543216616608.89404,
      },
    },
    tags: [
      "mineable",
      "pow",
      "sha-256",
      "store-of-value",
      "state-channel",
      "coinbase-ventures-portfolio",
      "three-arrows-capital-portfolio",
      "polychain-capital-portfolio",
      "binance-labs-portfolio",
      "blockchain-capital-portfolio",
      "boostvc-portfolio",
      "cms-holdings-portfolio",
      "dcg-portfolio",
      "dragonfly-capital-portfolio",
      "electric-capital-portfolio",
      "fabric-ventures-portfolio",
      "framework-ventures-portfolio",
      "galaxy-digital-portfolio",
      "huobi-capital-portfolio",
      "alameda-research-portfolio",
      "a16z-portfolio",
      "1confirmation-portfolio",
      "winklevoss-capital-portfolio",
      "usv-portfolio",
      "placeholder-ventures-portfolio",
      "pantera-capital-portfolio",
      "multicoin-capital-portfolio",
      "paradigm-portfolio",
      "btc-ecosystem",
    ],
    circulating_supply: 19338925,
  },
  {
    id: 1027,
    name: "ETH",
    symbol: "eth",
    quote: {
      USD: {
        price: 1879.106279804727,
        volume_24h: 8547118173.328249,
        market_cap: 226352963332.91113,
      },
    },
    tags: [
      "pos",
      "smart-contracts",
      "ethereum-ecosystem",
      "coinbase-ventures-portfolio",
      "three-arrows-capital-portfolio",
      "polychain-capital-portfolio",
      "binance-labs-portfolio",
      "blockchain-capital-portfolio",
      "boostvc-portfolio",
      "cms-holdings-portfolio",
      "dcg-portfolio",
      "dragonfly-capital-portfolio",
      "electric-capital-portfolio",
      "fabric-ventures-portfolio",
      "framework-ventures-portfolio",
      "hashkey-capital-portfolio",
      "kenetic-capital-portfolio",
      "huobi-capital-portfolio",
      "alameda-research-portfolio",
      "a16z-portfolio",
      "1confirmation-portfolio",
      "winklevoss-capital-portfolio",
      "usv-portfolio",
      "placeholder-ventures-portfolio",
      "pantera-capital-portfolio",
      "multicoin-capital-portfolio",
      "paradigm-portfolio",
      "injective-ecosystem",
    ],
    circulating_supply: 120457776,
  },
  {
    id: 825,
    name: "USDT",
    symbol: "usdt",
    quote: {
      USD: {
        price: 1.0002832333026646,
        volume_24h: 24498324296.96136,
        market_cap: 80130473095.69414,
      },
    },
    tags: [
      "payments",
      "stablecoin",
      "asset-backed-stablecoin",
      "avalanche-ecosystem",
      "solana-ecosystem",
      "arbitrum-ecosytem",
      "moonriver-ecosystem",
      "injective-ecosystem",
      "bnb-chain",
      "usd-stablecoin",
      "optimism-ecosystem",
    ],
    circulating_supply: 80107783903.49002,
  },
  {
    id: 1839,
    name: "BNB",
    symbol: "bnb",
    quote: {
      USD: {
        price: 312.96169070135613,
        volume_24h: 540096241.8773509,
        market_cap: 49412654458.02039,
      },
    },
    tags: [
      "marketplace",
      "centralized-exchange",
      "payments",
      "smart-contracts",
      "alameda-research-portfolio",
      "multicoin-capital-portfolio",
      "bnb-chain",
    ],
    circulating_supply: 157887230.0545323,
  },
];

export const listResponse = {
  data: currencyList,
  timestamp: "2023-04-05T10:41:24.799Z",
};
